### ISSUE TITLE
la ricerca ID_DFS in realtà non fa parte delle ricerche informate.

### ISSUE THREAD

**Issue by DennisTurco** [MarkGotLasagna/ai#3]
la ID_DFS è un algoritmo di ricerca non informato perchè non utilizza la funzione euristica per stimare il percorso migliore, ma è applicata indipendemente dall'albero in questione.

https://github.com/MarkGotLasagna/ai/blob/master/LESSONS/MARKDOWN/Lezione22.md?plain=1#L60C25-L60C25

**Comment by MarkGotLasagna** [comment]
Grazie della correzione :+1: 
Mi forniresti il timestamp della lezione in cui questo viene confermato? :smiley:

**Comment by MarkGotLasagna** [comment]
Grazie della correzione :+1: 

0d7d191
